version: '3'

services:
  trackskip-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"

  trackskip-cli:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run ./cli.go
